# Generated by Django 6.1.1 on 2026-10-01 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'ordering': ['nombre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('HUMEDAD', 'Humedad'), ('TEMPERATURA', 'Temperatura'), ('RADIACION', 'Radiación')], max_length=20)),
                ('unidad', models.CharField(help_text='Humedad: %, temperatura: °C, radiación: W/m².', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensores', to='monitoreo.parcela')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha y hora')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='monitoreo.sensor')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
                'ordering': ['-fecha_hora', '-pk'],
            },
        ),
    ]
